### ISSUE TITLE
[Bug]: win版使用命令行运行study出现报错

### ISSUE THREAD

**Issue by lyh0402** [heyibear/study_xxqg_download#12]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/heyibear/study_xxqg_download/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v0.1.6

### 运行环境

Windows (64)

### 运行架构

AMD64

### 运行方式

可执行文件（release的二进制）文件运行

### 重现步骤

登录账号后,在命令行使用study 1

### 期望的结果是什么？

正常运行学习

### 实际的结果是什么？

![image](https://user-images.githubusercontent.com/117897681/230349989-0e414ed0-7a5c-4a1c-ae70-7b15b9bb8e57.png)

### 日志记录（可选）

```golang
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running, locked to thread]:
study_xxqg/cli.study.func2(0xc0004961a0)
        study_xxqg/cli/shell.go:53 +0xb4
github.com/desertbit/grumble.(*App).RunCommand(0xc0001a9ea0, {0xc000496180?, 0x7?, 0x1721aa8?})
        github.com/desertbit/grumble@v1.1.3/app.go:270 +0x19f
github.com/desertbit/grumble.(*App).runShell(0xc0001a9ea0)
        github.com/desertbit/grumble@v1.1.3/app.go:469 +0x4c6
github.com/desertbit/grumble.(*App).Run(0xc0001a9ea0)
        github.com/desertbit/grumble@v1.1.3/app.go:401 +0x570
github.com/desertbit/grumble.Main(0xc0001a9ea0?)
        github.com/desertbit/grumble@v1.1.3/grumble.go:36 +0x19
study_xxqg/cli.RunCli()
        study_xxqg/cli/shell.go:31 +0xc6
study_xxqg/utils/stop.Stop(...)
        study_xxqg/utils/stop/stop_windows.go:15
main.main()
        study_xxqg/main.go:228 +0x44d
```

**Comment by heyibear** [comment]
加我 [Telegram ](https://t.me/heyibear)
